help:
	@echo

frontend: ## Install Frontend component
	@sh frontend.sh

mongodb: ## Install Mongodb component
	@sh mongodb.sh

catalogue: ## Install Catalogue component
	@sh catalogue.sh

redis: ## Install Redis component
	@sh redis.sh

user: ## Install User component
	@sh redis.sh

cart: ## Install Cart component
	@sh cart

mysql: ## Install Mysql component
	@sh mysql.sh

shipping: ## Install Shipping component
	@sh shipping.sh

payment: ## Install Payment component
	@sh payment.sh

rabbitmq: ## Install Rabbitmq component
	@sh rabbitmq.sh