help:
	@echo

frontend:
	@sh frontend.sh

mongodb:
	@sh mongodb.sh

catalogue:
	@sh catalogue.sh

redis:
	@sh redis.sh

user:
	@sh redis.sh

cart:
	@sh cart

mysql:
	@sh mysql.sh

shipping:
	@sh shipping.sh

payment:
	@sh payment.sh

rabbitmq:
	@sh rabbitmq.sh